---
- name: LVOL Install deps
  package:
    name: lvm2
    state: present

- set_fact:
    lvol_vg_name: "{{ item.vg_name }}"
    lvol_vg_pv: "{{ item.vg_pv }}"
    lvol_lv_dev: "{{ item.lv_dev }}"
  with_items:
    - "{{ disk_lvol }}"

- name: "Check how many disks to setup"
  debug:
    msg: "{{ lvol_lv_dev }}"

- name: LVOL Setup VG
  lvg:
    vg: "{{ lvol_vg_name }}"
    pvs: "{{ lvol_vg_pv }}"

- name: "LVOL Setup LV"
  include: lvm-vol.yml
  with_items: "{{ lvol_lv_dev }}"
  loop_control:
    loop_var: item_vol

- set_fact:
    disk_devices: "{{ lvol_lv_dev }}"
