#!/bin/bash

PATH="${PATH}:/usr/sbin"

for blkdev in $( nvme list | awk '/^\/dev/ { print $1 }' ) ; do
  mapping="/dev/$(nvme id-ctrl --raw-binary "${blkdev}" | cut -c3073-3104 | tr -s ' ' | sed 's/ $//g')"
  ( test -b "${blkdev}" && test -L "${mapping}" ) || ln -fs "${blkdev}" "${mapping}"
done

